### ISSUE TITLE
Issues when building for macOS

### ISSUE THREAD

**Issue by dgovil** [Autodesk/bifrost-usd#3]
Hi, 
Thanks for releasing this! I found a couple minor issues when building on macOS that I figured I should report here.

1. You need to request the macOS SDK when using xcrun to get the SDK path
in `platform_sdk_Darwin.cmake` you have two instances of this on line 47/57 that use need `--sdk macosx` added to the arguments. I believe this used to be optional, but seems to be required now.

2. The CMake build fails if using the Xcode generator. Using the Unix Makefiles generator works fine, but maybe it's worth calling out in the build instructions to use the Makefile generator?
The error is

```
CMake Error in cmake/bifusd/src/config/CMakeLists.txt:
  The custom command generating

    /Users/dhruvgovil/Projects/bifrost-usd/apple/build_scripts/build/bifrost_usd_build_maya2023/cmake/bifusd/src/config/bifusd/config/CfgCompilerMacros.cpp

  is attached to multiple targets:

    cg-CfgCompilerMacros.h-0acc790d41c
    hc-CfgCompilerMacros.h-0acc790d41c

  but none of these is a common dependency of the other(s).  This is not
  allowed by the Xcode "new build system".
```

Cheers!

**Comment by frenchdog** [comment]
Hi @dgovil,
Thanks for this very first issue on bifrost-usd project 😀 !
About the `--sdk macosx` argument, we will definitely consider that!
About the CMake Generator, as mentioned in the README, we encourage to use Ninja (`cmake -G Ninja`).
The Unix Makefiles should work fine on Mac and Linux but Ninja is required on Windows.
We will also take a look at this problem soon.
Thanks

**Comment by frenchdog** [comment]
The first issue (missing "--sdk macosx") is resolved by https://github.com/Autodesk/bifrost-usd/pull/10
@dgovil I'm going to close your issue and will create a new one for the second point (the Xcode Generator support).
